# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] 
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[shlvl]
disabled = false
threshold = 1
symbol = "â†•ï¸ "

[shell]
fish_indicator = 'ó°ˆº '
powershell_indicator = 'ï‘ _'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = true

[os]
format = "$symbol "
symbols.Ubuntu = "î¯‰"
disabled = false

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold blue)'
show_notifications=true 
notification_timeout=200

[conda]
symbol= 'ğŸ '
format = 'on [$symbol\[$environment\]](bold green) '

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[git_metrics]
disabled=false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[package]
format = 'via [ğŸ $version](208 bold) '

[python]
disabled=true
